name: JFRRS

services:

  database:
    image: postgres:latest
    ports:  
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jfrrs
    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: node:16-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app  # mount current folder to docker image
    command: "npm run dev"
    working_dir: /app


  # scraper:
  #   image: python:3.10
    
    

volumes:
  database: